"""Source facts established by live requests. Partial coverage stays partial."""

from __future__ import annotations

import csv
from pathlib import Path

COLUMNS = [
    "source_id",
    "source_name",
    "url",
    "access_method",
    "live_status",
    "fields_observed",
    "filters_available",
    "pagination_or_coverage",
    "restrictions",
    "cost",
    "used_for_rows",
]


def rows() -> list[dict[str, str]]:
    return [
        {
            "source_id": "sos_html_search",
            "source_name": "Iowa SOS business entity search",
            "url": "https://sos.iowa.gov/search/business/Search.aspx",
            "access_method": "Firecrawl browser actions. Direct curl returned Cloudflare HTTP 403.",
            "live_status": "search form submitted; KING CONSTRUCTION returned Results 1-16 of 16; PLUMBING returned Results 1-25 of 1000; business numbers 753682 and 694761 opened summary, filings, and officers",
            "fields_observed": "Business No.; Name; Status; name Type; Legal Name. The search page says it matches the first letters or words. The PLUMBING result page also included 10G HEATING COOLING PLUMBING LLC, which does not begin with PLUMBING, and it stopped at 1000 reported matches.",
            "filters_available": "none for county, NAICS, formation year, or active-only",
            "pagination_or_coverage": "Help page says a search returns at most 1000 results and that the office database holds 600,000+ entities. PLUMBING showed 25 rows on the first page of 1000. Later pages were not opened. This is not all active entities.",
            "restrictions": "Detail q= tokens are session-bound. A later scrape of a saved q= URL returned Invalid request. Help page liability statement: no warranty of completeness.",
            "cost": "Firecrawl credits on the shared local cap of 4000. No SOS fee for the HTML search.",
            "used_for_rows": "yes_partial_prefix_sample",
        },
        {
            "source_id": "sos_search_help",
            "source_name": "Iowa SOS business entities search help",
            "url": "https://sos.iowa.gov/businesses/business-entities-search-help",
            "access_method": "Firecrawl scrape HTTP 200",
            "live_status": "page opened",
            "fields_observed": "Documents name types (Legal, Fictitious, Former, and others). Says officers and directors are among information that can be viewed. Does not list historical officer snapshots, county, or industry.",
            "filters_available": "none",
            "pagination_or_coverage": "Maximum 1000 results per search. Noise words THE/AN stripped from the front; CORPORATION/INC stripped from the end.",
            "restrictions": "Customer service phone 515-281-5204 is printed for additional help.",
            "cost": "Firecrawl scrape",
            "used_for_rows": "documentation_only",
        },
        {
            "source_id": "sos_summary",
            "source_name": "Iowa SOS entity summary",
            "url": "https://sos.iowa.gov/search/business/summary.aspx",
            "access_method": "Same browser session as the business-number search",
            "live_status": "parsed business 753682",
            "fields_observed": "Business No.; Legal Name; Status; Type; State of Inc.; Modified; Expiration; Effective Date; Filing Date; Chapter; Names; Registered Agent name and city; Principal Office city. No NAICS. No county.",
            "filters_available": "none",
            "pagination_or_coverage": "One entity per number search",
            "restrictions": "Summary Filing Date matched the certificate of organization on 753682. It is not used as formation date unless the filings tab shows an organization or articles filing.",
            "cost": "Included in the entity browser session",
            "used_for_rows": "yes",
        },
        {
            "source_id": "sos_filings_index",
            "source_name": "Iowa SOS filings tab",
            "url": "https://sos.iowa.gov/search/business/filings.aspx",
            "access_method": "Click Filings in the same session",
            "live_status": "parsed 5 filings for 753682",
            "fields_observed": "Cert. No.; Pages; Filing Date; Effective Date; Type. Types observed: CERTIFICATE OF ORGANIZATION, ADMINISTRATIVE DISSOLUTION, REINSTATEMENT, BIENNIAL REPORT, REGISTERED OFFICE/AGENT CHANGE.",
            "filters_available": "none",
            "pagination_or_coverage": "Index for one entity. Not a statewide filing feed.",
            "restrictions": "The index does not contain officer before/after values.",
            "cost": "Included in the entity browser session",
            "used_for_rows": "yes",
        },
        {
            "source_id": "sos_officers_tab",
            "source_name": "Iowa SOS officers tab",
            "url": "https://sos.iowa.gov/search/business/officers.aspx",
            "access_method": "Click Officers in the same session",
            "live_status": "parsed business 753682",
            "fields_observed": "Columns Name, Address1, Address2, City, State, Zip, Type, Director. Value observed: None on file.",
            "filters_available": "none",
            "pagination_or_coverage": "Current list only. No prior snapshot and no as-of filing id on this tab.",
            "restrictions": "A single current list cannot emit OFFICER_ADDED, OFFICER_REMOVED, or OFFICER_ROLE_CHANGED.",
            "cost": "Included in the entity browser session",
            "used_for_rows": "current_list_only",
        },
        {
            "source_id": "sos_document_images",
            "source_name": "Iowa SOS filing document download",
            "url": "https://sos.iowa.gov/search/business/download.aspx",
            "access_method": "Click the certificate number in the same session. Response content-type application/pdf.",
            "live_status": "opened FT0273065 certificate of organization, A25753682 biennial report, FT0501653 change of registered agent for 753682",
            "fields_observed": "Certificate: organizer and initial registered agent. Biennial: LLC name, registered agent, principal office, agricultural-land question, family-farm question, authorized signer. Agent change: current agent name and new agent name. No member or officer roster on the biennial form.",
            "filters_available": "none",
            "pagination_or_coverage": "One document per certificate number. Session-bound URL.",
            "restrictions": "SSN redaction notice is printed on the filings tab. Street addresses from these documents are omitted from committed outputs. Agent and organizer are not owners.",
            "cost": "Separate Firecrawl browser session per document",
            "used_for_rows": "representative_documents_then_stop_if_no_officer_fields",
        },
        {
            "source_id": "sos_json_api",
            "source_name": "Iowa SOS Business Entity JSON API",
            "url": "https://api.sos.iowa.gov/",
            "access_method": "GET schema without auth returned HTTP 200. GET /businessEntity/id/19862 without a subscriber token returned HTTP 401. The swagger sample Authorization value also returned HTTP 401.",
            "live_status": "schema readable; entity payloads unauthorized",
            "fields_observed": "Public schema keys include EntityID, IncorporationDate, Chapter, Addresses.AddressType, Agent, Officers (current Name, Type, IsDirector, IsShareholder, address), Filings (description, dates, certificate number). No NAICS key. No county key.",
            "filters_available": "Documented routes: id, batch, modifiedsince, updatessince, lastmodified, lastupdate, maxentityid. Not usable without a subscription.",
            "pagination_or_coverage": "Docs say the API mirrors the HTML data. Last Update printed on the docs page: 7/10/2019. Modified means a content change. Update means an API database insert or update and may not mean the entity changed.",
            "restrictions": "Monthly subscription $2,400/year billed quarterly. Weekly subscription $10,400/year billed quarterly. Not purchased.",
            "cost": "subscription required; not purchased",
            "used_for_rows": "no",
        },
        {
            "source_id": "data_iowa_active_entities",
            "source_name": "Active Iowa Business Entities dataset",
            "url": "https://data.iowa.gov/catalog/dataset/554",
            "access_method": "Firecrawl cache returned the dataset description. A later live scrape returned HTTP 404. A browser action returned server error 386114062. Homepage https://data.iowa.gov/ returned HTTP 200 after an earlier HEAD 500.",
            "live_status": "dataset file not downloaded",
            "fields_observed": "Cached description: legal name, type, effective date, registered agent name and address, principal office address, corp_number. 344639 rows. Updated monthly. Data last updated September 08, 2026 on that cached page. No industry field in the description. No officer history.",
            "filters_available": "not verified; the file was not downloaded",
            "pagination_or_coverage": "Described as active entities registered with SOS. Sole proprietorships and some partnerships are absent. Not retrieved, so it is not a complete extract.",
            "restrictions": "Live catalog URL 404 during this run. CC BY stated on the cached page.",
            "cost": "no charge shown; download not completed",
            "used_for_rows": "no",
        },
        {
            "source_id": "contractor_registration",
            "source_name": "Iowa contractor registration pages",
            "url": "https://workforce.iowa.gov/contractor-registration",
            "access_method": "curl and Firecrawl",
            "live_status": "workforce.iowa.gov/contractor-registration returned a page-not-found body. contractor.iowa.gov redirects to https://laborportal.iwd.iowa.gov/iwd_portal/dashboards/contractor-home. That portal was not queried for records.",
            "fields_observed": "none",
            "filters_available": "unknown",
            "pagination_or_coverage": "no roster retrieved",
            "restrictions": "Trade was not enriched from a contractor roster in this run.",
            "cost": "none",
            "used_for_rows": "no",
        },
        {
            "source_id": "apify_jobs",
            "source_name": "Apify Indeed job actors",
            "url": "https://apify.com/store",
            "access_method": "Store search only. APIFY_TOKEN and APIFY_API_TOKEN were unset.",
            "live_status": "not run",
            "fields_observed": "none",
            "filters_available": "not used",
            "pagination_or_coverage": "not used",
            "restrictions": "Listed actors are pay-per-result. No prepaid balance was confirmed. No actor run was started.",
            "cost": "not spent",
            "used_for_rows": "no",
        },
        {
            "source_id": "bright_data",
            "source_name": "Bright Data",
            "url": "",
            "access_method": "environment check",
            "live_status": "BRIGHT_DATA_API_TOKEN unset",
            "fields_observed": "none",
            "filters_available": "not used",
            "pagination_or_coverage": "not used",
            "restrictions": "No request was sent.",
            "cost": "not spent",
            "used_for_rows": "no",
        },
        {
            "source_id": "claude",
            "source_name": "Claude summarization",
            "url": "",
            "access_method": "environment check",
            "live_status": "ANTHROPIC_API_KEY and CLAUDE_API_KEY unset",
            "fields_observed": "none",
            "filters_available": "not used",
            "pagination_or_coverage": "not used",
            "restrictions": "Final text uses deterministic templates. Claude did not run.",
            "cost": "not spent",
            "used_for_rows": "no",
        },
    ]


def write_feasibility(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=COLUMNS)
        writer.writeheader()
        writer.writerows(rows())
